# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Config": "00_core.ipynb",
         "URLs": "00_core.ipynb",
         "download_data": "00_core.ipynb",
         "file_extract": "00_core.ipynb",
         "download_file_from_google_drive": "00_core.ipynb",
         "untar_data": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://fastai.github.io/nbdev_template/"

git_url = "https://github.com/fastai/nbdev_template/tree/master/"

def custom_doc_links(name): return None
